# Generated by Django 5.1.5 on 2025-01-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthday',
            old_name='date',
            new_name='birthday',
        ),
    ]
